language: cpp
dist: trusty
sudo: false
compiler:
    - clang
    - gcc
os:
    - linux

before_script:
    - wget -q -O - https://sourceforge.net/projects/boost/files/boost/1.71.0/boost_1_71_0.tar.gz | tar -xz
    - cd boost_1_71_0 && ./bootstrap.sh --with-libraries=coroutine,context,chrono,system,thread,regex,filesystem,program_options
    - ./b2  --ignore-site-config && cd ..
    - mkdir build
    - cd build
    - cmake -DBOOST_ROOT=`pwd`/../boost_1_71_0 ..

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-10
    - g++-10
    - clang-12
    - lcov

script:
    - $CXX --version
    - make
    - make test
    - if [ "$CXX" == "g++-10" ]; then whereis gcov-10; fi
    - if [ "$CXX" == "g++-10" ]; then make coverage VERBOSE=1; bash <(curl -s https://codecov.io/bash) -X gcov; fi


install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-10"; export CC="gcc-10"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++"; fi
